[package]
name = "trajectorena"
version = "0.1.0"
authors = ["povilas.gintutis <povilas@oxylabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
